
all: binarySearch sortedGenerator 

binarySearch: binarySearch.c
	gcc -pedantic -Wall -o binarySearch binarySearch.c

sortedGenerator: sortedGenerator.c
	gcc -pedantic -Wall -o sortedGenerator sortedGenerator.c

clean:
	rm -f binarySearch sortedGenerator  *.o
